### ISSUE TITLE
Middleman 4

### ISSUE THREAD

**Issue by francescoagati** [isomorfeus/opal-webpack-loader#2]
Hi,
It should work with middleman 4 and webpack?

**Comment by janbiedermann** [comment]
yes it should.

However, the current jan biedermann/opal es6_import_export branch is already on opal 1.0 beta,
which may break things with opal gems that depend on opal-0.11
If you need opal 0.11 the use the es6_import_export branch with commit e3fdf16e8a657f7d9f9507207848a34953dced8d.

**Comment by francescoagati** [comment]
Thanks i Will try
