### ISSUE TITLE
Where is the actual opal code in the webpacker rails app?

### ISSUE THREAD

**Issue by eZii-jester-data** [isomorfeus/opal-webpack-loader#8]
Where is the actual opal code in the webpacker rails app?

https://github.com/isomorfeus/opal-webpack-loader/tree/master/example_apps/rails/railing_with_webpacker/app

I want to integrate THREE.rb into my [eZii OS](https://github.com/eZii-jester-data/ezii-os).

**Comment by janbiedermann** [comment]
Opal code goes here: https://github.com/isomorfeus/opal-webpack-loader/tree/master/example_apps/rails/railing_with_webpacker/app/opal

Just require files from the *_loader.rb in there or put more files in that directory, or however you like to organize your files.
